# Generated by Django 3.1.7 on 2021-03-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0002_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_address', to='covidapp.location')),
                ('business_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_business_name', to='covidapp.location')),
            ],
        ),
    ]
